### ISSUE TITLE
New compression argument in tiffile library crashes write_image function

### ISSUE THREAD

**Issue by D1rk123** [cicwi/flexDATA#11]
When writing tiff images with the write_image function, the tifffile library is used through the imageio library. In recent versions of the tifffile library the _compress_ argument of the imwrite function is removed and replaced by the _compression_ and _compressionargs_ arguments. This causes the write_image function to crash.

This happens with tifffile library versions newer than 2022.4.8

**Comment by askorikov** [comment]
Addressed by [d2377ab](https://github.com/cicwi/flexDATA/commit/d2377ab6aba50216a7beb9c3ab173a0f58791de9).
